// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoCPlK4jx_gmEgQlngk1Tkj4u0WHIQJqU',
    appId: '1:543915826668:web:7f1174d07c34987f47b4c9',
    messagingSenderId: '543915826668',
    projectId: 'sanchari4us-63ca9',
    authDomain: 'sanchari4us-63ca9.firebaseapp.com',
    storageBucket: 'sanchari4us-63ca9.appspot.com',
    measurementId: 'G-TF428THP5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALwD8QbEfL3zacZVzBCBHf1ryEYkTGcjQ',
    appId: '1:543915826668:android:9db35c90022c7e8747b4c9',
    messagingSenderId: '543915826668',
    projectId: 'sanchari4us-63ca9',
    storageBucket: 'sanchari4us-63ca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-S6UGlcL4eQjpiUP6v_USlRYCAuoz7Hs',
    appId: '1:543915826668:ios:c50a5adac6b32bfd47b4c9',
    messagingSenderId: '543915826668',
    projectId: 'sanchari4us-63ca9',
    storageBucket: 'sanchari4us-63ca9.appspot.com',
    androidClientId: '543915826668-rg15mp0j70joeuhnb8agpep0ls21gbed.apps.googleusercontent.com',
    iosClientId: '543915826668-i2oirc625lnjn8beagffhano3utq2qpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanchari',
  );
}
